<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { ElMessage } from 'element-plus'
import request from '@/utils/request'
const followups=ref([]), chronicRecords=ref([]), chronicId=ref(null), metric=ref({metric:'',value:''}), risk=ref(null), factors=ref({age:0,chronic_count:0,severe:false,emergency_symptom:false})
async function load(){try{const [followupRes,chronicRes]=await Promise.all([request.get('/p3/followups'),request.get('/p3/chronic')]);followups.value=followupRes.data||[];chronicRecords.value=chronicRes.data||[]}catch{followups.value=[];chronicRecords.value=[]}}
async function addMetric(){if(!chronicId.value||!metric.value.metric||!metric.value.value)return ElMessage.warning('请选择慢病档案并填写指标和数值');try{await request.post(`/p3/chronic/${chronicId.value}/metrics`,metric.value);ElMessage.success('指标已记录');metric.value={metric:'',value:''}}catch{/* request interceptor displays server detail */}}
async function assess(){risk.value=(await request.post('/p3/risk/assess',{factors:factors.value})).data}
async function complete(row){if(!row.task_id)return ElMessage.warning('当前没有待完成的随访任务');await request.post(`/p3/followups/${row.task_id}/complete`,{response:'已完成本次随访'});ElMessage.success('随访已完成');load()}
onMounted(load)
</script>
<template><div><h2 class="page-title">健康管理</h2><div class="modern-card"><h3>随访计划</h3><el-table :data="followups"><el-table-column prop="title" label="计划"/><el-table-column prop="next_date" label="下次日期"/><el-table-column label="操作"><template #default="{row}"><el-button v-if="row.can_complete" link type="primary" @click="complete(row)">完成</el-button></template></el-table-column></el-table><el-empty v-if="!followups.length" description="暂无随访计划"/></div><div class="modern-card"><h3>慢病指标记录</h3><el-space wrap><el-select v-model="chronicId" placeholder="请选择慢病档案" clearable style="width:180px"><el-option v-for="item in chronicRecords" :key="item.id" :label="`${item.disease}（档案 #${item.id}）`" :value="item.id"/></el-select><el-input v-model="metric.metric" placeholder="指标，如血压"/><el-input v-model="metric.value" placeholder="数值"/><el-button type="primary" @click="addMetric">记录指标</el-button></el-space><el-empty v-if="!chronicRecords.length" description="暂无慢病档案，请先创建档案" :image-size="50"/></div><div class="modern-card"><h3>风险评估</h3><el-space wrap><el-input-number v-model="factors.age" :min="0"/><el-input-number v-model="factors.chronic_count" :min="0"/><el-checkbox v-model="factors.severe">症状严重</el-checkbox><el-checkbox v-model="factors.emergency_symptom">疑似急症</el-checkbox><el-button type="primary" @click="assess">开始评估</el-button></el-space><el-alert v-if="risk" :title="`${risk.level}：${risk.score} 分`" :description="risk.advice" type="warning" show-icon/></div></div></template>
