-- AI智能医疗问诊平台 - MySQL 结构脚本
-- Docker 首次启动会自动执行；本地也可使用 scripts/import_sql.py 导入

CREATE DATABASE IF NOT EXISTS db_ai_medical DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE db_ai_medical;

CREATE TABLE IF NOT EXISTS t_admin (
  id INT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  username VARCHAR(50) NOT NULL COMMENT '用户名',
  password VARCHAR(255) NOT NULL COMMENT '密码',
  nickname VARCHAR(50) DEFAULT NULL COMMENT '昵称',
  avatar VARCHAR(255) DEFAULT NULL COMMENT '头像路径',
  phone VARCHAR(20) DEFAULT NULL COMMENT '手机号',
  email VARCHAR(100) DEFAULT NULL COMMENT '邮箱',
  status INT DEFAULT 1 COMMENT '状态',
  admin_role VARCHAR(20) DEFAULT 'admin' COMMENT '管理员类型: admin/root',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_admin_username (username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='管理员表';

CREATE TABLE IF NOT EXISTS t_user (
  id INT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  username VARCHAR(50) NOT NULL COMMENT '用户名',
  password VARCHAR(255) NOT NULL COMMENT '密码',
  real_name VARCHAR(50) DEFAULT NULL COMMENT '用户昵称',
  gender INT DEFAULT 1 COMMENT '性别:1男2女',
  age INT DEFAULT NULL COMMENT '年龄',
  phone VARCHAR(20) DEFAULT NULL COMMENT '手机号',
  avatar VARCHAR(255) DEFAULT NULL COMMENT '头像路径',
  allergy_history TEXT COMMENT '过敏史',
  status INT DEFAULT 1 COMMENT '状态',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_user_username (username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='患者用户表';

CREATE TABLE IF NOT EXISTS t_department (
  id INT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  name VARCHAR(50) NOT NULL COMMENT '科室名称',
  description VARCHAR(255) DEFAULT NULL COMMENT '科室描述',
  sort_order INT DEFAULT 0 COMMENT '排序',
  status INT DEFAULT 1 COMMENT '状态',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='科室表';

CREATE TABLE IF NOT EXISTS t_doctor (
  id INT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  username VARCHAR(50) NOT NULL COMMENT '登录账号',
  password VARCHAR(255) NOT NULL COMMENT '密码',
  real_name VARCHAR(50) NOT NULL COMMENT '医生姓名',
  department_id INT DEFAULT NULL COMMENT '所属科室ID',
  title VARCHAR(50) DEFAULT NULL COMMENT '职称',
  specialty VARCHAR(255) DEFAULT NULL COMMENT '擅长领域',
  introduction TEXT COMMENT '个人简介',
  avatar VARCHAR(255) DEFAULT NULL COMMENT '头像路径',
  phone VARCHAR(20) DEFAULT NULL COMMENT '手机号',
  status INT DEFAULT 1 COMMENT '状态',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_doctor_username (username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='医生表';

CREATE TABLE IF NOT EXISTS t_knowledge_file (
  id INT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  file_name VARCHAR(255) NOT NULL COMMENT '文件名',
  file_type VARCHAR(20) NOT NULL COMMENT '文件类型',
  file_size BIGINT DEFAULT 0 COMMENT '文件大小',
  file_path VARCHAR(500) NOT NULL COMMENT '存储路径',
  chunk_count INT DEFAULT 0 COMMENT '分块数量',
  vector_status INT DEFAULT 0 COMMENT '向量化状态',
  upload_by INT DEFAULT NULL COMMENT '上传人ID',
  upload_role VARCHAR(20) DEFAULT 'admin' COMMENT '上传人角色',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='知识库文件表';

CREATE TABLE IF NOT EXISTS t_knowledge_chunk (
  id INT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  file_id INT NOT NULL COMMENT '文件ID',
  chunk_index INT NOT NULL COMMENT '分块序号',
  content TEXT NOT NULL COMMENT '分块内容',
  vector_id VARCHAR(100) DEFAULT NULL COMMENT 'Chroma向量ID',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='知识库分块表';

CREATE TABLE IF NOT EXISTS t_consult_session (
  id INT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  user_id INT NOT NULL COMMENT '用户ID',
  title VARCHAR(200) DEFAULT '新会话' COMMENT '会话标题',
  message_count INT DEFAULT 0 COMMENT '消息数量',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI问诊会话表';

CREATE TABLE IF NOT EXISTS t_consult_message (
  id INT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  session_id INT NOT NULL COMMENT '会话ID',
  role VARCHAR(20) NOT NULL COMMENT '角色',
  content TEXT NOT NULL COMMENT '消息内容',
  references_json TEXT COMMENT '引用来源JSON',
  graph_json TEXT COMMENT '图谱实体JSON',
  cost_time INT DEFAULT 0 COMMENT '耗时毫秒',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI问诊消息表';

CREATE TABLE IF NOT EXISTS t_doctor_consult (
  id INT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  user_id INT NOT NULL COMMENT '患者ID',
  doctor_id INT DEFAULT NULL COMMENT '医生ID',
  chief_complaint TEXT NOT NULL COMMENT '主诉',
  status INT DEFAULT 0 COMMENT '状态',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='人工问诊工单表';

CREATE TABLE IF NOT EXISTS t_doctor_reply (
  id INT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  consult_id INT NOT NULL COMMENT '工单ID',
  doctor_id INT NOT NULL COMMENT '医生ID',
  content TEXT NOT NULL COMMENT '回复内容',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='医生回复表';

CREATE TABLE IF NOT EXISTS t_appointment (
  id INT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  user_id INT NOT NULL COMMENT '患者ID',
  doctor_id INT NOT NULL COMMENT '医生ID',
  department_id INT NOT NULL COMMENT '科室ID',
  visit_date DATE NOT NULL COMMENT '就诊日期',
  time_slot VARCHAR(20) NOT NULL COMMENT '时段',
  status INT DEFAULT 0 COMMENT '状态',
  remark VARCHAR(255) DEFAULT NULL COMMENT '备注',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='预约挂号表';

CREATE TABLE IF NOT EXISTS t_health_record (
  id INT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  user_id INT NOT NULL COMMENT '患者ID',
  doctor_id INT DEFAULT NULL COMMENT '医生ID',
  record_type VARCHAR(50) DEFAULT NULL COMMENT '档案类型',
  diagnosis VARCHAR(255) DEFAULT NULL COMMENT '诊断结果',
  treatment TEXT COMMENT '治疗方案',
  prescription TEXT COMMENT '处方',
  visit_date DATE DEFAULT NULL COMMENT '就诊日期',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='健康档案表';

CREATE TABLE IF NOT EXISTS t_article (
  id INT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  title VARCHAR(200) NOT NULL COMMENT '文章标题',
  category VARCHAR(50) DEFAULT NULL COMMENT '分类',
  cover VARCHAR(255) DEFAULT NULL COMMENT '封面图',
  summary VARCHAR(500) DEFAULT NULL COMMENT '摘要',
  content TEXT COMMENT '文章内容',
  view_count INT DEFAULT 0 COMMENT '浏览量',
  status INT DEFAULT 1 COMMENT '状态',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='健康科普文章表';

CREATE TABLE IF NOT EXISTS t_notice (
  id INT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  title VARCHAR(200) NOT NULL COMMENT '公告标题',
  content TEXT COMMENT '公告内容',
  status INT DEFAULT 1 COMMENT '状态',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='系统公告表';
